### ISSUE TITLE
App crashing 

### ISSUE THREAD

**Issue by toyeebgodo** [yTakkar/Single-Page-Social-Network#11]
I am getting this error below ( I experienced this when I ran "npm start" after installing nodemon globally). Please find the attached screenshot
![nodemon app crahsing](https://user-images.githubusercontent.com/23325937/33852048-40c272cc-deb9-11e7-8a05-46def6b4b5a7.png)

C:\Users\Toyeeb\react-mini-social-network\routes\api-routes.js:28
app.post('/explore', async function(req, res) {
                     ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Toyeeb\react-mini-social-network\app.js:20:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by yTakkar** [comment]
Nodemon crashes the app when there's any error in the project. In your case, nodejs version doesn't support async/await so upgrade nodejs
